export const discoverResponse = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/mExN6lJHmLeGjwDmDrNNjR4MdCq.jpg',
      genre_ids: [28, 12, 16, 35, 10751],
      id: 1011985,
      original_language: 'en',
      original_title: 'Kung Fu Panda 4',
      overview:
        'Po is gearing up to become the spiritual leader of his Valley of Peace, but also needs someone to take his place as Dragon Warrior. As such, he will train a new kung fu practitioner for the spot and will encounter a villain called the Chameleon who conjures villains from the past.',
      popularity: 6623.028,
      poster_path: '/wkfG7DaExmcVsGLR4kLouMwxeT5.jpg',
      release_date: '2024-03-02',
      title: 'Kung Fu Panda 4',
      video: false,
      vote_average: 6.869,
      vote_count: 198,
    },
    {
      adult: false,
      backdrop_path: '/47olX0FCvUCfAqlp8cK0O5fKLav.jpg',
      genre_ids: [16, 35, 878],
      id: 1239251,
      original_language: 'en',
      original_title: 'Megamind vs. the Doom Syndicate',
      overview:
        "Megamind's former villain team, The Doom Syndicate, has returned. Our newly crowned blue hero must now keep up evil appearances until he can assemble his friends (Roxanne, Ol' Chum and Keiko) to stop his former evil teammates from launching Metro City to the Moon.",
      popularity: 930.07,
      poster_path: '/yRZfiG1QpRkBc7fAmxfcR7Md5EC.jpg',
      release_date: '2024-03-01',
      title: 'Megamind vs. the Doom Syndicate',
      video: false,
      vote_average: 5.7,
      vote_count: 125,
    },
    {
      adult: false,
      backdrop_path: '/gklkxY0veMajdCiGe6ggsh07VG2.jpg',
      genre_ids: [16, 28, 12, 35, 10751],
      id: 940551,
      original_language: 'en',
      original_title: 'Migration',
      overview:
        'After a migrating duck family alights on their pond with thrilling tales of far-flung places, the Mallard family embarks on a family road trip, from New England, to New York City, to tropical Jamaica.',
      popularity: 824.18,
      poster_path: '/ldfCF9RhR40mppkzmftxapaHeTo.jpg',
      release_date: '2023-12-06',
      title: 'Migration',
      video: false,
      vote_average: 7.6,
      vote_count: 955,
    },
    {
      adult: false,
      backdrop_path: '/ehumsuIBbgAe1hg343oszCLrAfI.jpg',
      genre_ids: [16, 10751, 14, 12],
      id: 1022796,
      original_language: 'en',
      original_title: 'Wish',
      overview:
        'Asha, a sharp-witted idealist, makes a wish so powerful that it is answered by a cosmic force – a little ball of boundless energy called Star. Together, Asha and Star confront a most formidable foe - the ruler of Rosas, King Magnifico - to save her community and prove that when the will of one courageous human connects with the magic of the stars, wondrous things can happen.',
      popularity: 362.408,
      poster_path: '/AcoVfiv1rrWOmAdpnAMnM56ki19.jpg',
      release_date: '2023-11-13',
      title: 'Wish',
      video: false,
      vote_average: 6.6,
      vote_count: 880,
    },
    {
      adult: false,
      backdrop_path: '/a0GM57AnJtNi7lMOCamniiyV10W.jpg',
      genre_ids: [16, 12, 14],
      id: 508883,
      original_language: 'ja',
      original_title: '君たちはどう生きるか',
      overview:
        'While the Second World War rages, the teenage Mahito, haunted by his mother\'s tragic death, is relocated from Tokyo to the serene rural home of his new stepmother Natsuko, a woman who bears a striking resemblance to the boy\'s mother. As he tries to adjust, this strange new world grows even stranger following the appearance of a persistent gray heron, who perplexes and bedevils Mahito, dubbing him the "long-awaited one."',
      popularity: 361.132,
      poster_path: '/f4oZTcfGrVTXKTWg157AwikXqmP.jpg',
      release_date: '2023-07-14',
      title: 'The Boy and the Heron',
      video: false,
      vote_average: 7.442,
      vote_count: 1113,
    },
    {
      adult: false,
      backdrop_path: '/d1RHScaZc7I8j0lDke1c4AxI435.jpg',
      genre_ids: [28, 12, 16, 10751, 35],
      id: 9502,
      original_language: 'en',
      original_title: 'Kung Fu Panda',
      overview:
        'When the Valley of Peace is threatened, lazy Po the panda discovers his destiny as the "chosen one" and trains to become a kung fu hero, but transforming the unsleek slacker into a brave warrior won\'t be easy. It\'s up to Master Shifu and the Furious Five -- Tigress, Crane, Mantis, Viper and Monkey -- to give it a try.',
      popularity: 323.757,
      poster_path: '/wWt4JYXTg5Wr3xBW2phBrMKgp3x.jpg',
      release_date: '2008-06-04',
      title: 'Kung Fu Panda',
      video: false,
      vote_average: 7.269,
      vote_count: 10973,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [16, 14],
      id: 59300,
      original_language: 'ja',
      original_title: 'デンゼルを中心としたオリジナルアニメ',
      overview:
        "It's been four years since Meteor fell on Midgar. Denzel meets Reeve at an outskirts coffee shop about joining the World Regenesis Organization. Upon the request Denzel tells Reeve about what his life was like prior to the Meteor incident.",
      popularity: 304.605,
      poster_path: '/jn0qp1t7mExBze9qzy4pryFCbpm.jpg',
      release_date: '2009-04-16',
      title: 'Final Fantasy VII: On the Way to a Smile - Episode Denzel',
      video: false,
      vote_average: 5.6,
      vote_count: 26,
    },
    {
      adult: false,
      backdrop_path: '/hIeEpk2w1dnC9ly9ZJwwbunH2Cx.jpg',
      genre_ids: [16, 35, 18, 10751],
      id: 838240,
      original_language: 'xx',
      original_title: 'Robot Dreams',
      overview:
        "Dog lives in Manhattan and he's tired of being alone. One day he decides to build himself a robot, a companion. Their friendship blossoms, until they become inseparable, to the rhythm of 80's NYC. One summer night, Dog, with great sadness, is forced to abandon Robot at the beach. Will they ever meet again?",
      popularity: 282.547,
      poster_path: '/vSzOobYVu16MogSALNg1bjTaGc.jpg',
      release_date: '2023-10-20',
      title: 'Robot Dreams',
      video: false,
      vote_average: 7.472,
      vote_count: 125,
    },
    {
      adult: false,
      backdrop_path: '/zBm5QbduooRO8XYZB19SP1JJZe3.jpg',
      genre_ids: [16, 10751],
      id: 1205781,
      original_language: 'en',
      original_title: 'Dora: Say Hola to Adventure!',
      overview:
        'It’s Dora, the world’s most famous exploradora, like you’ve never seen her before! Join her and ALL her friends for BRAND NEW, magical adventures in the rainforest!',
      popularity: 270.032,
      poster_path: '/zN3BO43b0JAn1ZCpbwBH6KEP56U.jpg',
      release_date: '2023-11-10',
      title: 'Dora: Say Hola to Adventure!',
      video: false,
      vote_average: 6.6,
      vote_count: 10,
    },
    {
      adult: false,
      backdrop_path: '/9xfDWXAUbFXQK585JvByT5pEAhe.jpg',
      genre_ids: [16, 28, 12, 878],
      id: 569094,
      original_language: 'en',
      original_title: 'Spider-Man: Across the Spider-Verse',
      overview:
        'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society, a team of Spider-People charged with protecting the Multiverse’s very existence. But when the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must set out on his own to save those he loves most.',
      popularity: 269.783,
      poster_path: '/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
      release_date: '2023-05-31',
      title: 'Spider-Man: Across the Spider-Verse',
      video: false,
      vote_average: 8.378,
      vote_count: 5996,
    },
    {
      adult: false,
      backdrop_path: '/7gEfOcnoP2wAgtd7FYPsJopvJZ1.jpg',
      genre_ids: [16, 10751, 18, 12, 14],
      id: 1022789,
      original_language: 'en',
      original_title: 'Inside Out 2',
      overview:
        "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
      popularity: 257.162,
      poster_path: '/xeqXXTE1Cd3qNaAEOT6qbhhCsgJ.jpg',
      release_date: '2024-06-13',
      title: 'Inside Out 2',
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: '/9n2tJBplPbgR2ca05hS5CKXwP2c.jpg',
      genre_ids: [16, 10751, 12, 14, 35],
      id: 502356,
      original_language: 'en',
      original_title: 'The Super Mario Bros. Movie',
      overview:
        'While working underground to fix a water main, Brooklyn plumbers—and brothers—Mario and Luigi are transported down a mysterious pipe and wander into a magical new world. But when the brothers are separated, Mario embarks on an epic quest to find Luigi.',
      popularity: 256.579,
      poster_path: '/qNBAXBIQlnOThrVvA6mA2B5ggV6.jpg',
      release_date: '2023-04-05',
      title: 'The Super Mario Bros. Movie',
      video: false,
      vote_average: 7.686,
      vote_count: 8186,
    },
    {
      adult: false,
      backdrop_path: '/7BdxZXbSkUiVeCRXKD3hi9KYeWm.jpg',
      genre_ids: [16, 10751, 35],
      id: 49444,
      original_language: 'en',
      original_title: 'Kung Fu Panda 2',
      overview:
        'Po is now living his dream as The Dragon Warrior, protecting the Valley of Peace alongside his friends and fellow kung fu masters, The Furious Five - Tigress, Crane, Mantis, Viper and Monkey. But Po’s new life of awesomeness is threatened by the emergence of a formidable villain, who plans to use a secret, unstoppable weapon to conquer China and destroy kung fu. It is up to Po and The Furious Five to journey across China to face this threat and vanquish it. But how can Po stop a weapon that can stop kung fu? He must look to his past and uncover the secrets of his mysterious origins; only then will he be able to unlock the strength he needs to succeed.',
      popularity: 251.251,
      poster_path: '/mtqqD00vB4PGRt20gWtGqFhrkd0.jpg',
      release_date: '2011-05-25',
      title: 'Kung Fu Panda 2',
      video: false,
      vote_average: 7,
      vote_count: 6693,
    },
    {
      adult: false,
      backdrop_path: '/uT5G4fA7jKxlJNfwYPMm353f5AI.jpg',
      genre_ids: [28, 12, 16, 35, 10751],
      id: 140300,
      original_language: 'en',
      original_title: 'Kung Fu Panda 3',
      overview:
        'While Po and his father are visiting a secret panda village, an evil spirit threatens all of China, forcing Po to form a ragtag army to fight back.',
      popularity: 245.661,
      poster_path: '/oajNi4Su39WAByHI6EONu8G8HYn.jpg',
      release_date: '2016-01-23',
      title: 'Kung Fu Panda 3',
      video: false,
      vote_average: 6.894,
      vote_count: 5609,
    },
    {
      adult: false,
      backdrop_path: '/zLj0peaxy5y2SlC6wNIQ4V0pfqg.jpg',
      genre_ids: [16, 10751, 35, 14],
      id: 1139829,
      original_language: 'en',
      original_title: 'Orion and the Dark',
      overview:
        'A boy with an active imagination faces his fears on an unforgettable journey through the night with his new friend: a giant, smiling creature named Dark.',
      popularity: 219.195,
      poster_path: '/oT53tpbp12PfJ0ifCs71Viue8R8.jpg',
      release_date: '2024-02-01',
      title: 'Orion and the Dark',
      video: false,
      vote_average: 6.7,
      vote_count: 342,
    },
    {
      adult: false,
      backdrop_path: '/jr8tSoJGj33XLgFBy6lmZhpGQNu.jpg',
      genre_ids: [16, 12, 14, 35, 28, 10751],
      id: 315162,
      original_language: 'en',
      original_title: 'Puss in Boots: The Last Wish',
      overview:
        'Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.',
      popularity: 208.225,
      poster_path: '/kuf6dutpsT0vSVehic3EZIqkOBt.jpg',
      release_date: '2022-12-07',
      title: 'Puss in Boots: The Last Wish',
      video: false,
      vote_average: 8.243,
      vote_count: 7103,
    },
    {
      adult: false,
      backdrop_path: '/zMtBbNhROxPf0urHSBoZUnqJEwT.jpg',
      genre_ids: [16, 10751, 10402, 14, 35],
      id: 901362,
      original_language: 'en',
      original_title: 'Trolls Band Together',
      overview:
        "When Branch's brother, Floyd, is kidnapped for his musical talents by a pair of nefarious pop-star villains, Branch and Poppy embark on a harrowing and emotional journey to reunite the other brothers and rescue Floyd from a fate even worse than pop-culture obscurity.",
      popularity: 198.301,
      poster_path: '/bkpPTZUdq31UGDovmszsg2CchiI.jpg',
      release_date: '2023-10-12',
      title: 'Trolls Band Together',
      video: false,
      vote_average: 7.316,
      vote_count: 694,
    },
    {
      adult: false,
      backdrop_path: '/pA4sNvcohTNPx3AhEEeIu8gSt7h.jpg',
      genre_ids: [16, 35, 10751, 14, 10749, 12],
      id: 976573,
      original_language: 'en',
      original_title: 'Elemental',
      overview:
        'In a city where fire, water, land and air residents live together, a fiery young woman and a go-with-the-flow guy will discover something elemental: how much they have in common.',
      popularity: 197.232,
      poster_path: '/4Y1WNkd88JXmGfhtWR7dmDAo1T2.jpg',
      release_date: '2023-06-14',
      title: 'Elemental',
      video: false,
      vote_average: 7.666,
      vote_count: 3831,
    },
    {
      adult: false,
      backdrop_path: '/j29ekbcLpBvxnGk6LjdTc2EI5SA.jpg',
      genre_ids: [16, 10751, 12, 18, 35],
      id: 150540,
      original_language: 'en',
      original_title: 'Inside Out',
      overview:
        'From an adventurous balloon ride above the clouds to a monster-filled metropolis, Academy Award®-winning director Pete Docter (“Monsters, Inc.,” “Up”) has taken audiences to unique and imaginative places. In Disney and Pixar’s original movie “ Inside Out,” he will take us to the most extraordinary location of all—inside the mind.',
      popularity: 188.472,
      poster_path: '/2H1TmgdfNtsKlU9jKdeNyYL5y8T.jpg',
      release_date: '2015-06-09',
      title: 'Inside Out',
      video: false,
      vote_average: 7.917,
      vote_count: 20128,
    },
    {
      adult: false,
      backdrop_path: '/xIv4HuvPP9nL7PU9vq2PKOKFvhj.jpg',
      genre_ids: [28, 16],
      id: 116776,
      original_language: 'ja',
      original_title: 'ドラゴンボール 魔訶不思議大冒険',
      overview:
        "Master Roshi has succeeded at the one mission he valued most: to train Goku and Krillin to become ultimate fighters. So, he arranges for them to test their mettle at a competition hosted by Emperor Chiaotzu. Not everyone's playing by the rules, however, as a member of the ruler's household schemes to use the Dragonballs to extort money and power from the royal.",
      popularity: 179.378,
      poster_path: '/5aXG0B3TYTpQsodXzvYCkKQfpB1.jpg',
      release_date: '1988-07-09',
      title: 'Dragon Ball: Mystical Adventure',
      video: false,
      vote_average: 6.822,
      vote_count: 244,
    },
  ],
  total_pages: 2585,
  total_results: 51695,
};
