export const recommendation = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/wdwcOBMkt3zmPQuEMxB3FUtMio2.jpg',
      id: 271110,
      title: 'Captain America: Civil War',
      original_language: 'en',
      original_title: 'Captain America: Civil War',
      overview:
        'Following the events of Age of Ultron, the collective governments of the world pass an act designed to regulate all superhuman activity. This polarizes opinion amongst the Avengers, causing two factions to side with Iron Man or Captain America, which causes an epic battle between former allies.',
      poster_path: '/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg',
      media_type: 'movie',
      genre_ids: [12, 28, 878],
      popularity: 112.599,
      release_date: '2016-04-27',
      video: false,
      vote_average: 7.441,
      vote_count: 22034,
    },
    {
      adult: false,
      backdrop_path: '/jHxCeXnSchAuwHnmVatTgqMYdX8.jpg',
      id: 557,
      title: 'Spider-Man',
      original_language: 'en',
      original_title: 'Spider-Man',
      overview:
        'After being bitten by a genetically altered spider at Oscorp, nerdy but endearing high school student Peter Parker is endowed with amazing powers to become the superhero known as Spider-Man.',
      poster_path: '/gh4cZbhZxyTbgxQPxD0dOudNPTn.jpg',
      media_type: 'movie',
      genre_ids: [28, 878],
      popularity: 104.006,
      release_date: '2002-05-01',
      video: false,
      vote_average: 7.292,
      vote_count: 18233,
    },
    {
      adult: false,
      backdrop_path: '/uLtVbjvS1O7gXL8lUOwsFOH4man.jpg',
      id: 118340,
      title: 'Guardians of the Galaxy',
      original_language: 'en',
      original_title: 'Guardians of the Galaxy',
      overview:
        'Light years from Earth, 26 years after being abducted, Peter Quill finds himself the prime target of a manhunt after discovering an orb wanted by Ronan the Accuser.',
      poster_path: '/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg',
      media_type: 'movie',
      genre_ids: [28, 878, 12],
      popularity: 53.551,
      release_date: '2014-07-30',
      video: false,
      vote_average: 7.9,
      vote_count: 27262,
    },
    {
      adult: false,
      backdrop_path: '/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg',
      id: 19995,
      title: 'Avatar',
      original_language: 'en',
      original_title: 'Avatar',
      overview:
        'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
      poster_path: '/kyeqWdyUXW608qlYkRqosgbbJyK.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 14, 878],
      popularity: 148.261,
      release_date: '2009-12-15',
      video: false,
      vote_average: 7.58,
      vote_count: 30652,
    },
    {
      adult: false,
      backdrop_path: '/cyecB7godJ6kNHGONFjUyVN9OX5.jpg',
      id: 1726,
      title: 'Iron Man',
      original_language: 'en',
      original_title: 'Iron Man',
      overview:
        'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.',
      poster_path: '/78lPtwv72eTNqFW9COBYI0dWDJa.jpg',
      media_type: 'movie',
      genre_ids: [28, 878, 12],
      popularity: 103.44,
      release_date: '2008-04-30',
      video: false,
      vote_average: 7.642,
      vote_count: 25564,
    },
    {
      adult: false,
      backdrop_path: '/ziC23LkMYj8gToQQYQGWSGJCLNF.jpg',
      id: 82690,
      title: 'Wreck-It Ralph',
      original_language: 'en',
      original_title: 'Wreck-It Ralph',
      overview:
        "Wreck-It Ralph is the 9-foot-tall, 643-pound villain of an arcade video game named Fix-It Felix Jr., in which the game's titular hero fixes buildings that Ralph destroys. Wanting to prove he can be a good guy and not just a villain, Ralph escapes his game and lands in Hero's Duty, a first-person shooter where he helps the game's hero battle against alien invaders. He later enters Sugar Rush, a kart racing game set on tracks made of candies, cookies and other sweets. There, Ralph meets Vanellope von Schweetz who has learned that her game is faced with a dire threat that could affect the entire arcade, and one that Ralph may have inadvertently started.",
      poster_path: '/zWoIgZ7mgmPkaZjG0102BSKFIqQ.jpg',
      media_type: 'movie',
      genre_ids: [10751, 16, 35, 12],
      popularity: 78.881,
      release_date: '2012-11-01',
      video: false,
      vote_average: 7.337,
      vote_count: 11874,
    },
    {
      adult: false,
      backdrop_path: '/npDrIM6ZbuD7nUxI7ZzNBxs4IRF.jpg',
      id: 54138,
      title: 'Star Trek Into Darkness',
      original_language: 'en',
      original_title: 'Star Trek Into Darkness',
      overview:
        'When the crew of the Enterprise is called back home, they find an unstoppable force of terror from within their own organization has detonated the fleet and everything it stands for, leaving our world in a state of crisis.  With a personal score to settle, Captain Kirk leads a manhunt to a war-zone world to capture a one man weapon of mass destruction. As our heroes are propelled into an epic chess game of life and death, love will be challenged, friendships will be torn apart, and sacrifices must be made for the only family Kirk has left: his crew.',
      poster_path: '/7XrRkhMa9lQ71RszzSyVrJVvhyS.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 53.878,
      release_date: '2013-05-05',
      video: false,
      vote_average: 7.3,
      vote_count: 8817,
    },
    {
      adult: false,
      backdrop_path: '/m4F1KRK5jAoQHi2mKDFE2jFKEIb.jpg',
      id: 188927,
      title: 'Star Trek Beyond',
      original_language: 'en',
      original_title: 'Star Trek Beyond',
      overview:
        'The USS Enterprise crew explores the furthest reaches of uncharted space, where they encounter a mysterious new enemy who puts them and everything the Federation stands for to the test.',
      poster_path: '/yOnd3XQIg7JBmu0UuBjZyLdsxQD.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 48.369,
      release_date: '2016-07-07',
      video: false,
      vote_average: 6.8,
      vote_count: 6397,
    },
    {
      adult: false,
      backdrop_path: '/sAoUJAJtPqBLUcNNQHaVOjJ62oD.jpg',
      id: 166426,
      title: 'Pirates of the Caribbean: Dead Men Tell No Tales',
      original_language: 'en',
      original_title: 'Pirates of the Caribbean: Dead Men Tell No Tales',
      overview:
        "Thrust into an all-new adventure, a down-on-his-luck Capt. Jack Sparrow feels the winds of ill-fortune blowing even more strongly when deadly ghost sailors led by his old nemesis, the evil Capt. Salazar, escape from the Devil's Triangle. Jack's only hope of survival lies in seeking out the legendary Trident of Poseidon, but to find it, he must forge an uneasy alliance with a brilliant and beautiful astronomer and a headstrong young man in the British navy.",
      poster_path: '/qwoGfcg6YUS55nUweKGujHE54Wy.jpg',
      media_type: 'movie',
      genre_ids: [12, 28, 14],
      popularity: 75.778,
      release_date: '2017-05-23',
      video: false,
      vote_average: 6.652,
      vote_count: 11522,
    },
    {
      adult: false,
      backdrop_path: '/6YwkGolwdOMNpbTOmLjoehlVWs5.jpg',
      id: 99861,
      title: 'Avengers: Age of Ultron',
      original_language: 'en',
      original_title: 'Avengers: Age of Ultron',
      overview:
        'When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.',
      poster_path: '/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 103.249,
      release_date: '2015-04-22',
      video: false,
      vote_average: 7.273,
      vote_count: 22293,
    },
    {
      adult: false,
      backdrop_path: '/cDJ61O1STtbWNBwefuqVrRe3d7l.jpg',
      id: 10195,
      title: 'Thor',
      original_language: 'en',
      original_title: 'Thor',
      overview:
        "Against his father Odin's will, The Mighty Thor - a powerful but arrogant warrior god - recklessly reignites an ancient war. Thor is cast down to Earth and forced to live among humans as punishment. Once here, Thor learns what it takes to be a true hero when the most dangerous villain of his world sends the darkest forces of Asgard to invade Earth.",
      poster_path: '/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg',
      media_type: 'movie',
      genre_ids: [12, 14, 28],
      popularity: 100.175,
      release_date: '2011-04-21',
      video: false,
      vote_average: 6.766,
      vote_count: 20487,
    },
    {
      adult: false,
      backdrop_path: '/yFuKvT4Vm3sKHdFY4eG6I4ldAnn.jpg',
      id: 1771,
      title: 'Captain America: The First Avenger',
      original_language: 'en',
      original_title: 'Captain America: The First Avenger',
      overview:
        "During World War II, Steve Rogers is a sickly man from Brooklyn who's transformed into super-soldier Captain America to aid in the war effort. Rogers must stop the Red Skull – Adolf Hitler's ruthless head of weaponry, and the leader of an organization that intends to use a mysterious device of untold powers for world domination.",
      poster_path: '/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 56.778,
      release_date: '2011-07-22',
      video: false,
      vote_average: 6.999,
      vote_count: 20786,
    },
    {
      adult: false,
      backdrop_path: '/fctQU5MoXgJ5pNMljFzlEFXwfSu.jpg',
      id: 127585,
      title: 'X-Men: Days of Future Past',
      original_language: 'en',
      original_title: 'X-Men: Days of Future Past',
      overview:
        'The ultimate X-Men ensemble fights a war for the survival of the species across two time periods as they join forces with their younger selves in an epic battle that must change the past – to save our future.',
      poster_path: '/tYfijzolzgoMOtegh1Y7j2Enorg.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 85.881,
      release_date: '2014-05-15',
      video: false,
      vote_average: 7.525,
      vote_count: 14775,
    },
    {
      adult: false,
      backdrop_path: '/k6EOrckWFuz7I4z4wiRwz8zsj4H.jpg',
      id: 140607,
      title: 'Star Wars: The Force Awakens',
      original_language: 'en',
      original_title: 'Star Wars: The Force Awakens',
      overview:
        'Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.',
      poster_path: '/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg',
      media_type: 'movie',
      genre_ids: [12, 28, 878],
      popularity: 77.244,
      release_date: '2015-12-15',
      video: false,
      vote_average: 7.285,
      vote_count: 18794,
    },
    {
      adult: false,
      backdrop_path: '/fn4n6uOYcB6Uh89nbNPoU2w80RV.jpg',
      id: 315635,
      title: 'Spider-Man: Homecoming',
      original_language: 'en',
      original_title: 'Spider-Man: Homecoming',
      overview:
        'Following the events of Captain America: Civil War, Peter Parker, with the help of his mentor Tony Stark, tries to balance his life as an ordinary high school student in Queens, New York City, with fighting crime as his superhero alter ego Spider-Man as a new threat, the Vulture, emerges.',
      poster_path: '/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878, 18],
      popularity: 128.04,
      release_date: '2017-07-05',
      video: false,
      vote_average: 7.338,
      vote_count: 21057,
    },
    {
      adult: false,
      backdrop_path: '/1RWLMyC9KcFfcaoViMiJGSSZzzr.jpg',
      id: 100402,
      title: 'Captain America: The Winter Soldier',
      original_language: 'en',
      original_title: 'Captain America: The Winter Soldier',
      overview:
        'After the cataclysmic events in New York with The Avengers, Steve Rogers, aka Captain America is living quietly in Washington, D.C. and trying to adjust to the modern world. But when a S.H.I.E.L.D. colleague comes under attack, Steve becomes embroiled in a web of intrigue that threatens to put the world at risk. Joining forces with the Black Widow, Captain America struggles to expose the ever-widening conspiracy while fighting off professional assassins sent to silence him at every turn. When the full scope of the villainous plot is revealed, Captain America and the Black Widow enlist the help of a new ally, the Falcon. However, they soon find themselves up against an unexpected and formidable enemy—the Winter Soldier.',
      poster_path: '/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 45.016,
      release_date: '2014-03-20',
      video: false,
      vote_average: 7.667,
      vote_count: 18161,
    },
    {
      adult: false,
      backdrop_path: '/2nyaeISu2xIxIgZYNpX4UayY8PN.jpg',
      id: 141052,
      title: 'Justice League',
      original_language: 'en',
      original_title: 'Justice League',
      overview:
        "Fuelled by his restored faith in humanity and inspired by Superman's selfless act, Bruce Wayne and Diana Prince assemble a team of metahumans consisting of Barry Allen, Arthur Curry and Victor Stone to face the catastrophic threat of Steppenwolf and the Parademons who are on the hunt for three Mother Boxes on Earth.",
      poster_path: '/eifGNCSDuxJeS1loAXil5bIGgvC.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 98.396,
      release_date: '2017-11-15',
      video: false,
      vote_average: 6.091,
      vote_count: 12562,
    },
    {
      adult: false,
      backdrop_path: '/3s9O5af2xWKWR5JzP2iJZpZeQQg.jpg',
      id: 351286,
      title: 'Jurassic World: Fallen Kingdom',
      original_language: 'en',
      original_title: 'Jurassic World: Fallen Kingdom',
      overview:
        "Three years after Jurassic World was destroyed, Isla Nublar now sits abandoned. When the island's dormant volcano begins roaring to life, Owen and Claire mount a campaign to rescue the remaining dinosaurs from this extinction-level event.",
      poster_path: '/c9XxwwhPHdaImA2f1WEfEsbhaFB.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878, 53],
      popularity: 68.134,
      release_date: '2018-06-06',
      video: false,
      vote_average: 6.547,
      vote_count: 11354,
    },
    {
      adult: false,
      backdrop_path: '/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg',
      id: 299536,
      title: 'Avengers: Infinity War',
      original_language: 'en',
      original_title: 'Avengers: Infinity War',
      overview:
        'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
      poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
      media_type: 'movie',
      genre_ids: [12, 28, 878],
      popularity: 208.028,
      release_date: '2018-04-25',
      video: false,
      vote_average: 8.248,
      vote_count: 28659,
    },
    {
      adult: false,
      backdrop_path: '/9QusGjxcYvfPD1THg6oW3RLeNn7.jpg',
      id: 297802,
      title: 'Aquaman',
      original_language: 'en',
      original_title: 'Aquaman',
      overview:
        'Half-human, half-Atlantean Arthur Curry is taken on the journey of his lifetime to discover if he is worth of being a king.',
      poster_path: '/zdw7Wf97vsQ0YnGomxDqfcEdUjX.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 14],
      popularity: 97.59,
      release_date: '2018-12-07',
      video: false,
      vote_average: 6.9,
      vote_count: 13555,
    },
    {
      adult: false,
      backdrop_path: '/7lmBufEG7P7Y1HClYK3gCxYrkgS.jpg',
      id: 10138,
      title: 'Iron Man 2',
      original_language: 'en',
      original_title: 'Iron Man 2',
      overview:
        "With the world now aware of his dual life as the armored superhero Iron Man, billionaire inventor Tony Stark faces pressure from the government, the press and the public to share his technology with the military. Unwilling to let go of his invention, Stark, with Pepper Potts and James 'Rhodey' Rhodes at his side, must forge new alliances – and confront powerful enemies.",
      poster_path: '/6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg',
      media_type: 'movie',
      genre_ids: [12, 28, 878],
      popularity: 109.268,
      release_date: '2010-04-28',
      video: false,
      vote_average: 6.838,
      vote_count: 20287,
    },
  ],
  total_pages: 2,
  total_results: 40,
};
